#%RAML 0.8
---
title: Addons REST api for Mulesoft Buds project
version: v1.0
baseUri: http://buds.cloudhub.io/{version}/api

schemas:
  - plugins: !include plugins-schema.json
  - plugin: !include plugin-schema.json
  - updateSites: !include updateSites-schema.json
  - updateSite: !include updateSite-schema.json

/updateSites:
  get:
    description: Retrieves the entire list of update sites that are managed by the Mulesoft Buds application.
    responses:
      200:
        body:
          application/json:
            schema: updateSites
  /{updateSiteId}/plugins:
      get:
        description: Gets the list of the plugins that are in the update site
        responses:
         200:
           body:
             application/json:
               schema: plugins  
      /{pluginId}/incrementInstallationCount:
        post:
          description: Notifies that the plugin was installed into studio
          responses:
            200: ~
            404: ~
